# Generated by Django 5.0.4 on 2024-07-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('dataEnvio', models.DateField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVacina', models.CharField(max_length=105)),
                ('data', models.DateField(max_length=15)),
                ('horario', models.CharField(max_length=15)),
                ('publicoAlvo', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='nome',
            new_name='nomePaciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.AddField(
            model_name='administrador',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nomeProfissional',
            field=models.CharField(default='Maria', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
