# Generated by Django 5.0.4 on 2024-07-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avisos_vacinacao_delete_notificacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
