# Generated by Django 5.0.7 on 2024-08-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nome',
            new_name='username',
        ),
    ]
