# Generated by Django 5.0.7 on 2024-07-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_administrador_id_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='statusAdm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='statusPaciente',
            field=models.BooleanField(default=True),
        ),
    ]
