# Generated by Django 5.0.4 on 2024-08-12 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nome_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='idPaciente',
            field=models.ForeignKey(default='12345678909', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='imagem',
            field=models.CharField(default='https://cdn.prod.website-files.com/5fd2ba952bcd68835f2c8254/6545521d1914f328e7a94ac6_Professional-1.remini-enhanced-p-500.webp', max_length=255),
            preserve_default=False,
        ),
    ]
